library(ElemStatLearn)
library(randomForest)
library(e1071)
data(vowel.train)
data(vowel.test) 
vowel.train$y <- as.factor(vowel.train$y)
vowel.test$y <- as.factor(vowel.test$y)
set.seed(33833)
vowel.rf  <- randomForest(y ~ ., data=vowel.train)
vowel.svm <- svm(y ~ ., data=vowel.train)
pred.rf   <- predict(vowel.rf, vowel.test[,-1])
pred.svm  <- predict(vowel.svm, vowel.test[,-1])
#       5) What are the error rates for the two approaches on the test data set?
err.rf    <- sum(pred.rf != vowel.test$y)/length(pred.rf)
err.svm   <- sum(pred.svm != vowel.test$y)/length(pred.svm)
table(vowel.test$y, pred.rf)
table(vowel.test$y, pred.svm)
#       6) What is the error rate when the two methods agree on a prediction? 
agree.idx <- which(pred.rf == pred.svm)
err.both  <- sum(pred.rf[agree.idx] != vowel.test$y[agree.idx])/length(agree.idx)
